### PR TITLE
Logging: header blacklisting

### PR DESCRIPTION
**Pull request by d00rman**
This PR allows service developers to blacklist a specific set of headers when logging them. By default, `set-cookie`, `cookie`, `x-client-ip` and `x-forwarded-for` are removed. Developers may define their own set of headers to blacklist by adding a `log_header_blacklist` stanza to their service's configuration.

Bug: [T112072](https://phabricator.wikimedia.org/T112072)

### CODE REVIEW

**Comment by d00rman** [comment]
cc @Stype @wikimedia/services

**Comment by Pchelolo** [comment]
@d00rman In RESTBase we are white-listing the headers (see https://github.com/wikimedia/restbase/pull/366), why are we blacklisting them here?

**Comment by d00rman** [comment]
> In RESTBase we are white-listing the headers (see wikimedia/restbase#366), why are we blacklisting them here?

In my view it seems to be a more pragmatic solution. The service template is used by multiple services, so it's easier to say what not to log (with a sane default) then the other way round.

**Comment by Pchelolo** [comment]
Ok, fine with me, asked out of curiosity, LGTM

**Comment by d00rman** [comment]
Closing in favour of #48

**Pull request closed without merging**
