### PR TITLE
Auto-generate updates for the deploy repository

### PR DESCRIPTION
**Pull request by d00rman**
This PR extends `scripts/docker.js` with deploy-repo update capabilities. Concretely, it:
- creates the needed deploy repository outline
- adds/updates the submodule
- starts a container in which it:
  - installs the needed system dependencies
  - builds the node module dependencies
  - builds `heapdump`
- commits the ensemble with a pretty-formatted message
- sends the patch for review to Gerrit

It has been tested on Graphoid's repo, cf. https://gerrit.wikimedia.org/r/#/c/204497/ for the generated patch

As an added bonus, all commands being run inside the container are from now on run as an unprivileged user, mimicking the behaviour from production.

Bug: [T96128](https://phabricator.wikimedia.org/T96128)

### CODE REVIEW

**Comment by d00rman** [comment]
@gwicke please take a look, it works fabulously for me, but another pair of eyes would come in handy.

**Comment by gwicke** [comment]
This would be useful for other service-runner users like restbase as well. Should we move it over and make it accessible through a commandline parameter? Example: `node server --generate deploy-repo`

**Comment by d00rman** [comment]
> This would be useful for other service-runner users like restbase as well. Should we move it over and make it accessible through a commandline parameter?

Yup, my thoughts exactly. I will play with that tomorrow. It is already designed in such a way so as not to be template-specific, so it shouldn't be too hard to move.

BTW, the current version automatically sends the patch to Gerrit for review. Should we keep that as-is or perhaps should users enable it on the command line?

**Comment by gwicke** [comment]
> BTW, the current version automatically sends the patch to Gerrit for review. Should we keep that as-is or perhaps should users enable it on the command line?

That step could also be done by the deploy system, as it is fairly specific to our WMF setup, where it's run from, privileges etc.

**Comment by d00rman** [comment]
Moved to wikimedia/service-runner#30, so closing this one

**Pull request closed without merging**
