### PR TITLE
Clean-up

### PR DESCRIPTION
**Pull request by jdforrester**

### CODE REVIEW

**Comment by mdholloway** [comment]
👍

**Comment by jdforrester** [comment]
With these, there are three remaining security concerns from `npm audit`, all about the prototype pollution from `lodash` which we encountered a couple of months ago, and will need upstream bumps. They are `eslint-plugin-json` (which uses the abandoned `jshint`(!) for some reason),`nsp` (via `cli-table2`, but this project is now read-only, as the functionality moved into `npm`), and `service-runner` via `limitation` via the abandoned `kad`). In other words, I don't think we're going to get any movement on those three very soon, sadly.

Other non-latest dependencies are:

```
 domino  ^1.0.30  →  ^2.0.2
 ajv      ^5.5.0  →  ^6.5.0
 mocha    ^4.0.1  →  ^5.2.0
```
… leaving those be for now.

**Review by mdholloway — COMMENTED** [review]
Looks good to me.  I'll leave it to @d00rman or @Pchelolo to give final approval and merge. 

Side notes:
- Do any other services actually use domino?  Maybe it could come out of the template.
- mobileapps is already on major version 2 of domino; the other major version bumps you've foregone here work fine on mobileapps without further changes as well.

**Comment by jdforrester** [comment]
> mobileapps is already on major version 2 of domino; the other major version bumps you've foregone here work fine on mobileapps without further changes as well.

Yeah, I didn't want to make potentially-breaking changes without cause.

**Pull request merged**
