### PR TITLE
Update service-template-node to service-runner 2.8.3 with prometheus support.

### PR DESCRIPTION
**Pull request by ottomata**
This PR includes all the commits from #142, #148 and #153. It was easier to test these all together in one branch rather than merging the PRs individually.

### CODE REVIEW

**Comment by jdforrester** [comment]
Yeah, doing them all at once makes sense.

**Comment by ottomata** [comment]
I've merged these into EventGate and tested there.  Tests pass fine.  I also started eventgate server and made some requests and made sure that the prometheus metrics looked correct and included `express_router_request_duration_seconds_bucket`.

**Comment by Pchelolo** [comment]
Let's try! service-template isn't directly depended upon by anything, we can fix any issues that arise when updating individual services as they arise.

**Comment by ottomata** [comment]
Awesoome!

**Comment by ottomata** [comment]
Actually, I just realized we need another service-runner update too.
https://github.com/wikimedia/service-runner/pull/238

**Pull request merged**
