### PR TITLE
Update service-runner to v2.8.0

### PR DESCRIPTION
**Pull request by clarakosi**

### CODE REVIEW

**Comment by Pchelolo** [comment]
We need the same change in utils.js as done in eventstreams.

**Comment by mvolz** [comment]
What's the status on this? We're now getting warnings in master using the old metrics api for citoid. (`Calling 'Metrics.increment' directly is deprecated`)

**Comment by ottomata** [comment]
Let's get this merged!  What's needed?

**Comment by Pchelolo** [comment]
> Let's get this merged! What's needed?

I guess a review from you would be appreciated. then rebase and merge?

**Comment by ottomata** [comment]
Perhaps we can pull together all the various service-runner version update PRs and do it that way?  I'll see if I can do that with some git fu (of which my github variant is not strong)...

So this + #148 + #153.  I'll test that all together with EventGate and try to make a consolidated PR.

**Comment by Pchelolo** [comment]
Oh that's much more then I could even ask for! :)

**Comment by ottomata** [comment]
Included these commits in a consolidated PR #155

**Pull request closed without merging**
