### PR TITLE
Remove init scripts

### PR DESCRIPTION
**Pull request by berndsi**
AFAIK they are not used.

### CODE REVIEW

**Comment by berndsi** [comment]
For context we're starting a new project and want to use TypeScript. The Typescript output goes to the `dist` folder.
This commit is taken from https://gerrit.wikimedia.org/r/c/mediawiki/services/push-notifications/+/594351.
The TypeScript commit is currently still WIP: https://gerrit.wikimedia.org/r/c/mediawiki/services/push-notifications/+/594352

**Comment by mdholloway** [comment]
+1, I *think* these are obsolete now that services are to be launched on k8s.

**Comment by mvolz** [comment]
Since they're puppet files I thought maybe they're used by vagrant or something but they seem not to be - at least the ones in citoid don't seem to do anything. Maybe on tools / sourceforge? @akosiaris do you know what these did/do?

**Comment by Pchelolo** [comment]
These used to be examples on how you could set it up. indeed can remove now.

**Pull request merged**
