### PR TITLE
Delete unused static html file

### PR DESCRIPTION
**Pull request by Bhaarat-khatri**
delete unused static file and disable serving from app.js
bug: T261712

### CODE REVIEW

**Comment by Bhaarat-khatri** [comment]
can anybody tell me why this checked failed

**Comment by Bhaarat-khatri** [comment]
i have solved issue according to this https://phabricator.wikimedia.org/T263973

**Comment by aklapper** [comment]
No, https://phabricator.wikimedia.org/T263973 has nothing to do with this. See my comments in https://phabricator.wikimedia.org/T261712 ; I don't understand why this patch was proposed.

**Comment by aklapper** [comment]
Closing pull request as per discussion in https://phabricator.wikimedia.org/T261712 as this doesn't seem to be the right approach

**Pull request closed without merging**
